# Generated by Django 5.2

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailrecipient",
            name="unsubscribe_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "layout",
                    models.CharField(
                        choices=[("weekly_meeting", "Weekly meeting")],
                        default="weekly_meeting",
                        max_length=30,
                    ),
                ),
                (
                    "subject_template",
                    models.CharField(
                        default="This week's gathering - {{ meeting_date }}",
                        max_length=255,
                    ),
                ),
                (
                    "greeting",
                    models.CharField(default="Hello {{ first_name }},", max_length=255),
                ),
                ("standard_copy", models.TextField(blank=True)),
                (
                    "closing",
                    models.TextField(
                        default="We hope to see you there,\nSojourn Baptist Church"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("bilingual", "Bilingual"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_templates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "email template",
                "verbose_name_plural": "email templates",
                "ordering": ("name",),
            },
        ),
    ]
