# Generated by Django 5.2.17 on 2026-08-14 07:56

import django.db.models.deletion
import sermons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SermonCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "sermon collection",
                "verbose_name_plural": "sermon collections",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SermonTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "sermon tag",
                "verbose_name_plural": "sermon tags",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Sermon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("speaker", models.CharField(max_length=150)),
                ("sermon_date", models.DateField()),
                ("summary", models.TextField()),
                ("thesis", models.TextField()),
                ("main_scripture", models.CharField(max_length=150)),
                ("transcript", models.TextField(blank=True)),
                (
                    "media_file",
                    models.FileField(
                        upload_to=sermons.models.sermon_audio_upload_path,
                        validators=[sermons.models.validate_mp3],
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sermons",
                        to="sermons.sermoncollection",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="sermons", to="sermons.sermontag"
                    ),
                ),
            ],
            options={
                "ordering": ("-sermon_date", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["is_published", "sermon_date"],
                        name="sermons_ser_is_publ_f09951_idx",
                    ),
                    models.Index(
                        fields=["collection", "sermon_date"],
                        name="sermons_ser_collect_825034_idx",
                    ),
                ],
            },
        ),
    ]
