# Generated by Django 5.2.17 on 2026-09-03 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sermons', '0003_sermontranslation_translationjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationjob',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation_jobs', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='translationjob',
            name='object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='translationjob',
            name='target_field',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='translationjob',
            name='field',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='translationjob',
            name='sermon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation_jobs', to='sermons.sermon'),
        ),
        migrations.AddConstraint(
            model_name='translationjob',
            constraint=models.UniqueConstraint(condition=models.Q(('content_type__isnull', False), ('status', 'claimed')), fields=('content_type', 'object_id', 'language', 'field', 'status'), name='one_active_generic_translation_job'),
        ),
        migrations.AddConstraint(
            model_name='translationjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('content_type__isnull', True), ('sermon__isnull', False)), models.Q(('content_type__isnull', False), ('sermon__isnull', True)), _connector='OR'), name='translation_job_one_target'),
        ),
    ]
