# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        help_text="The image displayed in the homepage hero section.",
                        upload_to="site/hero/",
                    ),
                ),
                (
                    "hero_image_alt",
                    models.CharField(
                        blank=True,
                        help_text="Describe the image for visitors using a screen reader.",
                        max_length=255,
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="The small image shown in the browser tab.",
                        upload_to="site/favicon/",
                    ),
                ),
            ],
            options={
                "verbose_name": "site settings",
                "verbose_name_plural": "site settings",
            },
        ),
    ]
