# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(help_text="Role in English.", max_length=100),
                ),
                (
                    "role_es",
                    models.CharField(
                        blank=True,
                        help_text="Spanish role, if different from the English role.",
                        max_length=100,
                    ),
                ),
                ("bio", models.TextField(blank=True, help_text="Biography in English.")),
                ("bio_es", models.TextField(blank=True, help_text="Biography in Spanish.")),
                ("photo", models.ImageField(blank=True, upload_to="team/")),
                (
                    "photo_alt",
                    models.CharField(
                        blank=True,
                        help_text="Describe the photo for visitors using a screen reader.",
                        max_length=255,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "team member",
                "verbose_name_plural": "team members",
                "ordering": ("order", "name"),
            },
        ),
    ]
