# Generated by Django 5.2

from django.db import migrations, models
import django.db.models.deletion


def seed_about_content(apps, schema_editor):
    AboutPage = apps.get_model("core", "AboutPage")
    AboutSection = apps.get_model("core", "AboutSection")

    page, _ = AboutPage.objects.get_or_create(
        pk=1,
        defaults={
            "title_en": "About Sojourn Baptist Church",
            "title_es": "Acerca de la Iglesia Bautista Sojourn",
            "meta_description_en": (
                "Learn about Sojourn Baptist Church, our beliefs, bilingual "
                "ministry, and pastoral leadership."
            ),
            "meta_description_es": (
                "Conoce la Iglesia Bautista Sojourn, nuestras creencias, "
                "nuestro ministerio bilingüe y nuestro liderazgo pastoral."
            ),
        },
    )

    sections = (
        {
            "key": "intro",
            "title_en": "A church for our neighbors",
            "title_es": "Una iglesia para nuestros vecinos",
            "body_en": (
                "Sojourn Baptist Church is a Christian, Baptist church learning "
                "to walk faithfully together as a fully bilingual church in our "
                "local community."
            ),
            "body_es": (
                "La Iglesia Bautista Sojourn es una iglesia cristiana y bautista "
                "que aprende a caminar fielmente como una iglesia plenamente "
                "bilingüe en nuestra comunidad local."
            ),
            "display_order": 1,
        },
        {
            "key": "mission",
            "title_en": "Worship, faith, and welcome",
            "title_es": "Adoración, fe y bienvenida",
            "body_en": (
                "Sojourn Baptist Church exists to worship Jesus Christ, grow "
                "together in faith, and serve our local community as a fully "
                "bilingual church, with a particular desire to welcome and reach "
                "our Latino neighbors."
            ),
            "body_es": (
                "La Iglesia Bautista Sojourn existe para adorar a Jesucristo, "
                "crecer juntos en la fe y servir a nuestra comunidad local como "
                "una iglesia plenamente bilingüe, con un deseo especial de dar "
                "la bienvenida y alcanzar a nuestros vecinos latinos."
            ),
            "display_order": 2,
        },
        {
            "key": "beliefs",
            "title_en": "Rooted in the historic Christian faith",
            "title_es": "Arraigados en la fe cristiana histórica",
            "body_en": (
                "We affirm the historic Christian faith expressed in the "
                "Apostles' Creed and the Nicene Creed. As a Baptist church, our "
                "teaching is also shaped by the 1689 London Baptist Confession "
                "of Faith and the Heidelberg Catechism. Together, these documents "
                "help us understand and faithfully communicate what we believe "
                "about God, Scripture, salvation, the church, and Christian living."
            ),
            "body_es": (
                "Afirmamos la fe cristiana histórica expresada en el Credo de los "
                "Apóstoles y el Credo Niceno. Como iglesia bautista, nuestra "
                "enseñanza también está formada por la Confesión Bautista de Fe "
                "de Londres de 1689 y el Catecismo de Heidelberg. Juntos, estos "
                "documentos nos ayudan a entender y comunicar fielmente lo que "
                "creemos acerca de Dios, las Escrituras, la salvación, la iglesia "
                "y la vida cristiana."
            ),
            "display_order": 3,
        },
        {
            "key": "bilingual_ministry",
            "title_en": "Bilingual ministry",
            "title_es": "Ministerio bilingüe",
            "body_en": (
                "Pastor Blake brings a bilingual ministry shaped by his missionary "
                "service in Mexico. We want English- and Spanish-speaking neighbors "
                "to find a genuine welcome, faithful teaching, and a place to grow "
                "together."
            ),
            "body_es": (
                "El pastor Blake trae un ministerio bilingüe formado por su servicio "
                "misionero en México. Queremos que nuestros vecinos de habla inglesa "
                "y española encuentren una bienvenida sincera, enseñanza fiel y un "
                "lugar para crecer juntos."
            ),
            "display_order": 4,
        },
        {
            "key": "leadership",
            "title_en": "Pastoral leadership",
            "title_es": "Liderazgo pastoral",
            "body_en": "",
            "body_es": "",
            "display_order": 5,
        },
        {
            "key": "visitor_cta",
            "title_en": "Come and learn more about our church",
            "title_es": "Ven y conoce más acerca de nuestra iglesia",
            "body_en": (
                "We would be glad to meet you, worship with you, and help you "
                "find a place to begin."
            ),
            "body_es": (
                "Nos alegrará conocerte, adoraremos contigo y te ayudaremos a "
                "encontrar un lugar para comenzar."
            ),
            "display_order": 6,
        },
    )

    for section in sections:
        AboutSection.objects.get_or_create(
            page=page,
            key=section["key"],
            defaults=section,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_teammember"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_en", models.CharField(max_length=200)),
                ("title_es", models.CharField(blank=True, max_length=200)),
                ("meta_description_en", models.TextField(max_length=320)),
                (
                    "meta_description_es",
                    models.TextField(blank=True, max_length=320),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About page",
                "verbose_name_plural": "About page",
            },
        ),
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("intro", "Introduction"),
                            ("mission", "Mission"),
                            ("beliefs", "Beliefs"),
                            ("bilingual_ministry", "Bilingual ministry"),
                            ("leadership", "Leadership"),
                            ("visitor_cta", "Visitor call to action"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title_en", models.CharField(max_length=200)),
                ("title_es", models.CharField(blank=True, max_length=200)),
                ("body_en", models.TextField(blank=True)),
                ("body_es", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="core.aboutpage",
                    ),
                ),
            ],
            options={
                "ordering": ("display_order", "key"),
                "verbose_name": "About section",
                "verbose_name_plural": "About sections",
            },
        ),
        migrations.AddConstraint(
            model_name="aboutsection",
            constraint=models.UniqueConstraint(
                fields=("page", "key"),
                name="unique_about_section_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="aboutsection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    key__in=(
                        "intro",
                        "mission",
                        "beliefs",
                        "bilingual_ministry",
                        "leadership",
                        "visitor_cta",
                    )
                ),
                name="valid_about_section_key",
            ),
        ),
        migrations.RunPython(seed_about_content, migrations.RunPython.noop),
    ]
