# Generated by Django 5.2.17 on 2026-09-03 16:07

import django.db.models.deletion
import os

from django.db import migrations, models


def migrate_legacy_media(apps, schema_editor):
    """Reference existing storage keys without copying or deleting objects."""
    SiteSettings = apps.get_model("core", "SiteSettings")
    TeamMember = apps.get_model("core", "TeamMember")
    MediaAsset = apps.get_model("media", "MediaAsset")

    def get_asset(storage_key, label):
        storage_key = getattr(storage_key, "name", storage_key)
        if not storage_key:
            return None
        asset = MediaAsset.objects.filter(file=storage_key).first()
        if asset:
            return asset
        filename = os.path.basename(storage_key)
        return MediaAsset.objects.create(
            file=storage_key,
            name=label or filename,
            original_filename=filename[:255],
            storage_status="unverified",
        )

    site_settings = SiteSettings.objects.filter(pk=1).first()
    if site_settings:
        site_settings.hero_image_asset = get_asset(
            site_settings.hero_image,
            "Legacy homepage hero image",
        )
        site_settings.favicon_asset = get_asset(
            site_settings.favicon,
            "Legacy browser favicon",
        )
        site_settings.hero_image_alt_en = site_settings.hero_image_alt
        site_settings.save(
            update_fields=(
                "hero_image_asset",
                "favicon_asset",
                "hero_image_alt_en",
            )
        )

    for member in TeamMember.objects.exclude(photo=""):
        member.photo_asset = get_asset(member.photo, f"Legacy photo: {member.name}")
        member.save(update_fields=("photo_asset",))


def reverse_legacy_media(apps, schema_editor):
    SiteSettings = apps.get_model("core", "SiteSettings")
    TeamMember = apps.get_model("core", "TeamMember")
    SiteSettings.objects.update(
        hero_image_asset=None,
        favicon_asset=None,
        hero_image_alt_en="",
    )
    TeamMember.objects.update(photo_asset=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_theme'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='favicon_site_settings', to='media.mediaasset'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image_alt_en',
            field=models.CharField(blank=True, help_text='English alternative text for the selected hero image.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image_alt_es',
            field=models.CharField(blank=True, help_text='Optional Spanish alternative text for the selected hero image.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hero_site_settings', to='media.mediaasset'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_icon_1_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='homepage_icon_1_site_settings', to='media.mediaasset'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_icon_2_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='homepage_icon_2_site_settings', to='media.mediaasset'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_icon_3_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='homepage_icon_3_site_settings', to='media.mediaasset'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_icon_4_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='homepage_icon_4_site_settings', to='media.mediaasset'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_icon_5_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='homepage_icon_5_site_settings', to='media.mediaasset'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_icon_6_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='homepage_icon_6_site_settings', to='media.mediaasset'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_icon_7_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='homepage_icon_7_site_settings', to='media.mediaasset'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo_alt_es',
            field=models.CharField(blank=True, help_text='Optional Spanish alternative text for the selected photo.', max_length=255),
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_member_photos', to='media.mediaasset'),
        ),
        migrations.RunPython(migrate_legacy_media, reverse_legacy_media),
    ]
