# Generated by Django 5.2.17 on 2026-09-03 17:29

from django.db import migrations, models


STATEMENTS = (
    "Centered on God",
    "On Mission Together",
    "Dependent on God",
    "Journeying Homeward",
    "Driven by the Word",
    "In Supernatural Community",
    "Made Holy by Grace",
)


def seed_homepage_statements(apps, schema_editor):
    SiteSettings = apps.get_model("core", "SiteSettings")
    site_settings = SiteSettings.objects.filter(pk=1).first()
    if not site_settings:
        return
    updates = {
        f"homepage_statement_{number}_en": statement
        for number, statement in enumerate(STATEMENTS, start=1)
    }
    SiteSettings.objects.filter(pk=site_settings.pk).update(**updates)


def unseed_homepage_statements(apps, schema_editor):
    SiteSettings = apps.get_model("core", "SiteSettings")
    updates = {
        f"homepage_statement_{number}_en": ""
        for number in range(1, 8)
    }
    SiteSettings.objects.update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings_favicon_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_statement_1_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_statement_1_es',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_statement_2_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_statement_2_es',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_statement_3_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_statement_3_es',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_statement_4_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_statement_4_es',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_statement_5_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_statement_5_es',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_statement_6_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_statement_6_es',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_statement_7_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_statement_7_es',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(seed_homepage_statements, unseed_homepage_statements),
    ]
