# Generated by Django 5.2.17 on 2026-09-03

from django.db import migrations


STATEMENTS_EN = (
    "Centered on God",
    "On Mission Together",
    "Dependent on God",
    "Journeying Homeward",
    "Driven by the Word",
    "In Supernatural Community",
    "Made Holy by Grace",
)

STATEMENTS_ES = (
    "Centrados en Dios",
    "Juntos en misión",
    "Dependientes de Dios",
    "Caminando hacia el hogar",
    "Impulsados por la Palabra",
    "En una comunidad sobrenatural",
    "Santificados por la gracia",
)


def seed_statements_es(apps, schema_editor):
    SiteSettings = apps.get_model("core", "SiteSettings")
    site_settings = SiteSettings.objects.filter(pk=1).first()
    if not site_settings:
        return
    updates = {
        f"homepage_statement_{number}_es": statement
        for number, statement in enumerate(STATEMENTS_ES, start=1)
    }
    SiteSettings.objects.filter(pk=site_settings.pk).update(**updates)


def unseed_statements_es(apps, schema_editor):
    SiteSettings = apps.get_model("core", "SiteSettings")
    updates = {
        f"homepage_statement_{number}_es": ""
        for number in range(1, 8)
    }
    SiteSettings.objects.update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_sitesettings_homepage_statement_1_en_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_statements_es, unseed_statements_es),
    ]
