# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_seed_homepage_statement_spanish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="theme",
            field=models.CharField(
                choices=[
                    ("dark", "Dark"),
                    ("light", "Light"),
                    ("medium", "Medium"),
                    ("workshop", "Workshop"),
                ],
                default="dark",
                help_text="Choose the visual theme for the entire public website.",
                max_length=10,
            ),
        ),
    ]
