# Generated by Django 5.2.17 on 2026-09-28 13:38

import django.db.models.deletion
from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


def link_word_driven_sermon(apps, schema_editor):
    """Connect the existing published Word-Driven message when it is present."""
    SiteSettings = apps.get_model("core", "SiteSettings")
    Sermon = apps.get_model("sermons", "Sermon")
    sermon = Sermon.objects.filter(
        slug="a-word-driven-church",
        is_published=True,
    ).first()
    if sermon:
        SiteSettings.objects.filter(
            pk=1,
            homepage_word_driven_sermon__isnull=True,
        ).update(homepage_word_driven_sermon_id=sermon.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_social_links_and_prospectus'),
        ('sermons', '0004_translationjob_content_type_translationjob_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_word_driven_sermon',
            field=models.ForeignKey(
                blank=True,
                help_text=_(
                    'Published sermon linked from the Word-Driven homepage distinctive.'
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='homepage_word_driven_settings',
                to='sermons.sermon',
            ),
        ),
        migrations.RunPython(link_word_driven_sermon, migrations.RunPython.noop),
    ]
