# Generated by Django 5.2.17 on 2026-09-03 15:44

import django.db.models.deletion
import media.models
import media.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCleanupIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=512)),
                ('reason', models.CharField(max_length=255)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'media cleanup issue',
                'verbose_name_plural': 'media cleanup issues',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='MediaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('normalized_name', models.CharField(editable=False, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'media tag',
                'verbose_name_plural': 'media tags',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=media.models.media_asset_upload_path, validators=[media.validators.validate_image_upload])),
                ('name', models.CharField(max_length=255)),
                ('original_filename', models.CharField(editable=False, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('alt_text_en', models.CharField(blank=True, help_text='Default English alternative text; placements may override it.', max_length=255)),
                ('alt_text_es', models.CharField(blank=True, help_text='Optional Spanish default alternative text.', max_length=255)),
                ('media_type', models.CharField(choices=[('image', 'Image')], default='image', max_length=20)),
                ('mime_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('file_size', models.PositiveBigIntegerField(default=0, editable=False)),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('sha256', models.CharField(blank=True, editable=False, max_length=64)),
                ('storage_status', models.CharField(choices=[('present', 'Present'), ('missing', 'Missing'), ('unverified', 'Unverified')], default='unverified', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media_assets', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='assets', to='media.mediatag')),
            ],
            options={
                'verbose_name': 'media asset',
                'verbose_name_plural': 'media assets',
                'ordering': ('-created_at', 'name'),
            },
        ),
    ]
